### ISSUE TITLE
Not able to upsert record from one org to another org Using externalId

### ISSUE THREAD

**Issue by saketn302** [forcedotcom/Data-Migration-Tool#5]
Hi , 

I tried to upsert product record from my one dev org to another dev org using an external ID, 
but it is throwing error. 

2019-04-10 21:25:26 ERROR SfdcApiServiceImpl:1169 - ObjectName: Product2 ,originalIndex: 0 ,sourceId: 01t0o000007Ei9KAAS ,Error Message: External_ID__c not specified

I tried to access External Id I am able to get the name in class.

Can you please help me , I am stuck here. 

Thanks 
Saket gupta

**Comment by anoop-76** [comment]
@saketn302 : Do you have External_ID__c populated in the source org? If not, please make sure to populate it.

**Comment by saketn302** [comment]
Hi  Anoop thanks for your response ,
 Yes it is populated in both org .

Thanks

Saket

**Comment by anoop-76** [comment]
Does running user has proper FLS for the external field? Please share the json mapping if possible.

**Comment by saketn302** [comment]
Hi Anoop ,

Thanks for you frequent response.

Yes , FLS and Everything is fine on both org for external ID field

JSON is very simple I am Just trying to update 1 record.

[
  {
    "parent": "Product2",
     "where": "ID='01t0o000007Ei9K'",
     "externalIdField": "External_ID__c"
   }
]

Thanks
Saket Gupta

**Comment by anoop-76** [comment]
This is fixed.

**Comment by saketn302** [comment]
Working for me thanks Anoop .
