### ISSUE TITLE
Unknown lifecycle phase "pl"

### ISSUE THREAD

**Issue by lopezjl91** [forcedotcom/Data-Migration-Tool#8]
I downloaded the tool, followed installation instructions, and finally tried to run one of the sample commands. I tried to run the Migrate Accounts with Opportunities and Assets with the command 
`mvn exec:java -Dexec.mainClass="migrator.module.client.MigrateAccountsHierarchical.java" pl datamigrator-module` 
but in return I got the following error:

`[ERROR] Unknown lifecycle phase "pl". You must specify a valid lifecycle phase or a goal in the format <plugin-prefix>:<goal> or <plugin-group-id>:<plugin-artifact-id>[:<plugin-version>]:<goal>. Available lifecycle phases are: validate, initialize, generate-sources, process-sources, generate-resources, process-resources, compile, process-classes, generate-test-sources, process-test-sources, generate-test-resources, process-test-resources, test-compile, process-test-classes, test, prepare-package, package, pre-integration-test, integration-test, post-integration-test, verify, install, deploy, pre-clean, clean, post-clean, pre-site, site, post-site, site-deploy. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/LifecyclePhaseNotFoundException`

Is there something I'm missing from the setup? I haven't changed anything on any file. 
I tried to run 
`mvn clean install`  before the actual command and that didn't help either. 

Any help is appreciated.
Thanks!

**Comment by anoop-76** [comment]
@lopezjl91 

Try:

mvn exec:java -Dexec.mainClass="migrator.module.client.MigrateAccountsHierarchical.java" -pl datamigrator-module

**Comment by anoop-76** [comment]
@lopezjl91 : Was your issue resolved? Let me know if not, we can open it again.
